# Generated by Django 5.2.1 on 2025-05-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('bank', models.CharField(max_length=200)),
                ('credit_card', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('rg', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
