# Generated by Django 5.2.1 on 2025-07-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('chassi', models.CharField(max_length=17, unique=True)),
                ('renavan', models.CharField(max_length=11, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('ano_modelo', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('combustivel', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=50)),
                ('potencia', models.CharField(max_length=20)),
                ('cambio', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=30)),
                ('numero_portas', models.IntegerField()),
                ('numero_passageiros', models.IntegerField()),
                ('capacidade_carga', models.CharField(blank=True, max_length=20, null=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('proprietario_nome', models.CharField(max_length=200)),
                ('proprietario_cpf', models.CharField(max_length=14)),
                ('proprietario_endereco', models.TextField()),
                ('situacao', models.CharField(default='Ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
